export enum PORTAL_TYPE {
  DYNAMIC_COMPONENT = 'DYNAMIC_COMPONENT',
  CACHE = 'CACHE',
  TESTING = 'TESTING',
  ESM = 'ESM',
  NOTES = 'NOTES',
  FONT = 'FONT',
  BREAKING_CHANGE = 'BREAKING_CHANGE',
  DEPRECATIONS = 'DEPRECATIONS',
  DOCUMENTS = 'DOCUMENTS',
  HOME = 'HOME'
}

export const PORTAL_MAP = new Map<PORTAL_TYPE, number>([
  [PORTAL_TYPE.DYNAMIC_COMPONENT, 0],
  [PORTAL_TYPE.CACHE, 1],
  [PORTAL_TYPE.TESTING, 2],
  [PORTAL_TYPE.ESM, 3],
  [PORTAL_TYPE.FONT, 4],
  [PORTAL_TYPE.NOTES, 5],
  [PORTAL_TYPE.BREAKING_CHANGE, 6],
  [PORTAL_TYPE.DEPRECATIONS, 7],
  [PORTAL_TYPE.DOCUMENTS, 8],
  [PORTAL_TYPE.HOME, 9],
])

export const TYPE_TITLE_MAP = new Map<PORTAL_TYPE, string>([
  [PORTAL_TYPE.HOME, 'Notes of Angular v13'],
  [PORTAL_TYPE.DYNAMIC_COMPONENT, 'Component API updates'],
  [PORTAL_TYPE.CACHE, 'Cache Management'],
  [PORTAL_TYPE.TESTING, 'Angular Testing Improvements'],
  [PORTAL_TYPE.ESM, 'ESM supported on the ng serve'],
  [PORTAL_TYPE.FONT, 'Inline Resource (Adobe font)'],
  [PORTAL_TYPE.NOTES, 'Other Features'],
  [PORTAL_TYPE.BREAKING_CHANGE, 'Breaking Changes'],
  [PORTAL_TYPE.DEPRECATIONS, 'Deprecations'],
  [PORTAL_TYPE.DOCUMENTS, 'Official Documents']
]);